language: node_js
node_js: 9
dist: trusty
cache: yarn

# Runs before each stage
install:
  - npm i -g firebase-tools
  - yarn

# Define order and conditions of stages
stages:
  - test
  - name: deploy-staging
    if: branch = master
  - name: deploy-production
    if: branch = production

# Define stages and their scripts
jobs:
  include:
    - stage: test
      script: yarn test

    - stage: deploy-staging
      script: yarn deploy-rules
    - script: yarn deploy-api

    - stage: deploy-production
      script: yarn deploy-rules-production
    - script: yarn deploy-api-production
