language: node_js
node_js: 9
dist: trusty
cache: yarn

# Define stages and their scripts
jobs:
  include:
    - stage: test
      script: yarn test

deploy:
  provider: script
  script: bash scripts/deploy.sh production
  on:
    branch: production
