language: node_js
node_js: 7
dist: trusty

install:
  - yarn install

script:
  - yarn test

deploy:
  - provider: script
    script: yarn deploy-rules && yarn deploy-api
    on:
      branch: ci-deploy
