language: node_js
node_js: 9
dist: trusty
cache: yarn

install:
  # - yarn global add firebase-tools
  - yarn install
  - npm i -g firebase-tools

script:
  - yarn test

# before_deploy:
#   - yarn add firebase-tools

# deploy:
#   - provider: script
#     script: yarn deploy-rules && yarn deploy-api
#     on:
#       branch: ci-deploy

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy to firebase
      script: yarn deploy-rules
      script: yarn deploy-api
