language: node_js
node_js: 9
dist: trusty

install:
  - yarn install

script:
  - yarn test

before_deploy:
  - yarn add firebase-tools

deploy:
  - provider: script
    script: yarn deploy-rules && yarn deploy-api
    on:
      branch: ci-deploy
