language: node_js
node_js: 9
dist: trusty
cache: yarn

# Define stages and their scripts
jobs:
  include:
    - stage: test
      script: yarn test

    - stage: deploy-staging
      if: branch IN (master, ci-deploy)
      script:
        - yarn deploy-rules
        - yarn deploy-api

    - stage: deploy-production
      if: branch = production
      script:
        - yarn deploy-rules-production
        - yarn deploy-api-production
